# Generated by Django 5.0.4 on 2024-06-04 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
            },
        ),
        migrations.CreateModel(
            name='In_Charge_Of',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='A cargo de')),
            ],
            options={
                'verbose_name': 'A cargo de',
                'verbose_name_plural': 'A cargo de',
            },
        ),
        migrations.CreateModel(
            name='Progresive_School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Escuela Programa')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronym', models.CharField(max_length=10, verbose_name='Sigla')),
                ('name', models.CharField(max_length=100, verbose_name='Seccion')),
            ],
            options={
                'verbose_name': 'Seccion',
                'verbose_name_plural': 'Secciones',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Proveedoredor')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Training_Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ambito de Formacion')),
            ],
            options={
                'verbose_name': 'Ambito de Formacion',
                'verbose_name_plural': 'Ambitos de Formacion',
            },
        ),
        migrations.CreateModel(
            name='Type_Training_Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tipo de Accion')),
            ],
            options={
                'verbose_name': 'Tipo de Accion Formativa',
                'verbose_name_plural': 'Tipos de Accion Formativa',
            },
        ),
        migrations.CreateModel(
            name='Teacher_Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_duoc', models.CharField(max_length=12, verbose_name='ID DUOC')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre Acción Formativa')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Ano')),
                ('duration', models.FloatField(verbose_name='Duración')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('itinerary', models.CharField(blank=True, max_length=255, null=True, verbose_name='Itinerario')),
                ('characterization', models.CharField(choices=[('Habilitante', 'Habilitante'), ('Voluntario', 'Voluntario'), ('Obligatorio', 'Obligatorio')], max_length=20, verbose_name='Caracterización')),
                ('state', models.CharField(choices=[('Participación', 'Participación'), ('Aprovado', 'Aprovado'), ('Reprobado', 'Reprobado')], max_length=20, verbose_name='Estado')),
                ('period', models.CharField(choices=[('PRIMER SEMESTRE', 'PRIMER SEMESTRE'), ('SEGUNDO SEMESTRE', 'SEGUNDO SEMESTRE'), ('SR', 'SR'), ('TAV', 'TAV')], max_length=20, verbose_name='Periodo')),
                ('end_month', models.CharField(choices=[('ENERO', 'ENERO'), ('FEBRERO', 'FEBRERO'), ('MARZO', 'MARZO'), ('ABRIL', 'ABRIL'), ('MAYO', 'MAYO'), ('JUNIO', 'JUNIO'), ('JULIO', 'JULIO'), ('AGOSTO', 'AGOSTO'), ('SEPTIEMBRE', 'SEPTIEMBRE'), ('OCTUBRE', 'OCTUBRE'), ('NOVIEMBRE', 'NOVIEMBRE'), ('DICIEMBRE', 'DICIEMBRE'), ('SR', 'SR')], max_length=10, verbose_name='Mes de finalizacion')),
                ('post_choice', models.CharField(choices=[('COLABORADOR', 'COLABORADOR'), ('EXTERNO', 'EXTERNO'), ('DOCENTE', 'DOCENTE'), ('SR', 'SR')], max_length=15, verbose_name='Cargo')),
                ('created_at', models.DateTimeField(null=True, verbose_name='Fecha de creacion')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='Fecha de actualizacion')),
                ('in_charge_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.in_charge_of', verbose_name='A cargo de')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.section', verbose_name='Seccion')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.supplier', verbose_name='Proveedor')),
                ('tranin_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.training_area', verbose_name='Ambito de Formacion')),
                ('type_training_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.type_training_action', verbose_name='Tipo de Accion Formativa')),
            ],
            options={
                'verbose_name': 'Accion Formativa',
                'verbose_name_plural': 'Accion Formativa',
            },
        ),
    ]
