# Generated by Django 5.0.4 on 2024-06-04 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progresive_school',
            options={'verbose_name': 'Escuela Programa', 'verbose_name_plural': 'Escuela Programa'},
        ),
    ]
